// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 01/05/2025 20:05:17
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Users/jiper/OneDrive - univ-rouen.fr/Bureau/SIO/PortfolioV2/portfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/jiper/OneDrive - univ-rouen.fr/Bureau/SIO/PortfolioV2/portfolio/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/jiper/OneDrive - univ-rouen.fr/Bureau/SIO/PortfolioV2/portfolio/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/jiper/OneDrive - univ-rouen.fr/Bureau/SIO/PortfolioV2/portfolio/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/jiper/OneDrive - univ-rouen.fr/Bureau/SIO/PortfolioV2/portfolio/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/jiper/OneDrive - univ-rouen.fr/Bureau/SIO/PortfolioV2/portfolio/plugins/**/*.{js,ts,mjs}","C:/Users/jiper/OneDrive - univ-rouen.fr/Bureau/SIO/PortfolioV2/portfolio/composables/**/*.{js,ts,mjs}","C:/Users/jiper/OneDrive - univ-rouen.fr/Bureau/SIO/PortfolioV2/portfolio/utils/**/*.{js,ts,mjs}","C:/Users/jiper/OneDrive - univ-rouen.fr/Bureau/SIO/PortfolioV2/portfolio/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/jiper/OneDrive - univ-rouen.fr/Bureau/SIO/PortfolioV2/portfolio/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/jiper/OneDrive - univ-rouen.fr/Bureau/SIO/PortfolioV2/portfolio/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;